baseURL = 'https://dbvamsi.github.io/'
languageCode = 'en-us'
title = 'Bhaskar Vamsi ka Personal Blog'
theme="hugo-paper"
author = "Bhaskar Vamsi Dontaraju"
enableInlineShortcodes = true
ignoreErrors = ["error-remote-getjson"]


[params]
    # show header social icons
    
    github = 'DBVamsi'       # github.com/DBVamsi
    
    

    # show home page profile
    
    name = 'Bhaskar Vamsi Dontaraju'
    bio = 'Technical writer | Technology Enthusiast'

[menu]

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10

  [[menu.main]]
    identifier = "Resume"
    name = "Resume"
    url = "/Resume/"
    weight = 10

   [[menu.main]]
    identifier = "Contact"
    name = "Contact"
    url = "/Contact/"
    weight = 10  

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[privacy]

  [privacy.twitter]
    disabled = false
    enableDNT = true
    simple = true

  [privacy.instagram]
    disabled = false
    simple = true

  [privacy.youtube]
    disabled = false
    privacyEnhanced = true